apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-demo-
spec:
  taskRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/tektoncd/catalog.git
    - name: revision
      value: main
    - name: pathInRepo
      value: task/git-clone/0.9/git-clone.yaml
  params:
  - name: url
    value: https://github.com/redhat-appstudio/infra-deployments.git
  workspaces:
  - name: output
    emptyDir: {}
